version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: finance_api_postgres
    environment:
      POSTGRES_USER: finapi
      POSTGRES_PASSWORD: finapi
      POSTGRES_DB: finapi
    ports:
      - '5432:5432'
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
